# Generated by Django 4.1.3 on 2022-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='amount_of_funds',
            field=models.IntegerField(default=0),
        ),
    ]
