# Generated by Django 4.1.3 on 2022-11-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_users_amount_of_funds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='mail',
        ),
    ]
